version: 2
jobs:
   build:
     working_directory: ~/DevOps_Microservices/project-ml-microservice-kubernetes/
     docker:
       - image: python:3.7.3-stretch
     steps:
       - checkout
       - restore_cache:
           keys:
             - v1-dependencies-{{ checksum "requirements.txt" }}
             - v1-dependencies-
       - run:
           name: install dependencies
           command: |
             python3 -m venv venv
             . venv/bin/activate
             cd project-ml-microservice-kubernetes
             pwd
             make install
             wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
             chmod +x /bin/hadolint
       - save_cache:
           paths:
             - ./venv
           key: v1-dependencies-{{ checksum "requirements.txt" }}
       - run:
           name: run lint
           command: |
             . venv/bin/activate
             make lint
